config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts do
    post "/like", to: "likes#like_toggle"
    resources :comments, only: [:create, :destroy]
  end
  
  resources :follows, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :likes
    has_many :liked_users, through: :likes, source: :user
    has_many :comments
    mount_uploader :image, PostUploader
    #has_and_belongs_to_many :tags
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_and_belongs_to_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments
  has_many :follower_relations, foreign_key: "followed_id", class_name: "Follow"
  has_many :followers, through: :follower_relations, source: :follower
  has_many :following_relations, foreign_key: "follower_id", class_name: "Follow"
  has_many :followings, through: :following_relations, source: :followed
  mount_uploader :profile, ProfileUploader
  def is_like?(post)
    Like.find_by(user_id: self.id, post_id: post.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :check_ownership!, only:[:destroy]

    def create
        if user_signed_in?
            new_comment = Comment.new(content: params[:content], post_id: params[:post_id], user_id: current_user.id) 
            new_comment.save 
            redirect_back fallback_location: root_path
        else
            redirect_to root_path
        end
    end
    
    def destroy
        @comment.destroy
        redirect_back fallback_location: root_path
    end
    
    private
        def check_ownership!
            @comment = Comment.find_by(id: params[:id])
            redirect_back fallback_location: root_path if @comment.user.id!=current_user.id
        end

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
    before_action :authenticate_user!
    
    def create
        Follow.create(followed_id: params[:followed_id], follower_id: current_user.id)
        redirect_back fallback_location: root_path
    end
    def destroy
        Follow.find_by(followed_id: params[:id], follower_id: current_user.id).destroy
        redirect_back fallback_location: root_path
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!
    def like_toggle
        like = Like.find_by(user_id: current_user.id, post_id: params[:post_id]) 
        if like.nil? 
            Like.create(user_id: current_user.id, post_id: params[:post_id]) 
        else 
            like.destroy 
        end 
        
        redirect_back fallback_location: root_path

    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :check_ownership, only:[:edit, :update, :destroy]

  def index
    @posts=Post.all.order('created_at desc')
    if current_user!=nil
      @posts_count=current_user.posts.length
    end
    
  end
  
  def new
    
  end
  
  def show
    @user=User.find_by(id:params[:id])
    @posts=Post.all.order('created_at desc')
    
    if current_user!=nil
      @posts_count=current_user.posts.length
    end
  end
  
  def create
    new_post = Post.new(user_id: current_user.id, content: params[:content], image: params[:image])
    if new_post.save
      redirect_to root_path
    else
      redirect_to new_post_path
    end
  end
  
  def edit
  end
  
  def update
    
    @post.content=params[:content]
    @post.image=params[:image] if params[:image].present?
    
    if @post.save
      redirect_to root_path
    else
      render :edit
    end
  end
  
  def destroy
    
    @post.destroy
    redirect_to root_path
  end
  
  private
  def check_ownership
    @post=Post.find_by(id:params[:id])
    redirect_to root_path if @post.user.id!=current_user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JJ_story</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
      /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
      .img-size{
          width:auto; height:auto;
          max-width:700px;
          max-height:500px;
          margin-left: auto;
          margin-right: auto;
      }
      .row.content {height: 1500px}
      
      /* Set gray background color and 100% height */
      .sidenav {
          height: 100%;
          width: auto;
          position: fixed;
          z-index: 1;
          top: 0;
          left: 0;
          background-color: white;
          overflow-x: hidden;
          padding-top: 20px;
          color: black;
          
      }
      .sidenav a {
          padding: 6px 8px 6px 16px;
          text-decoration: none;
          font-size: 15px;
          color: #d9d9d9;
          display: block;
      }
      
      /* Add a black background color to the top navigation */
      .topnav {
          background-color: #333;
          overflow: hidden;
      }
      
      /* Style the links inside the navigation bar */
      .topnav a {
          float: left;
          color: #f2f2f2;
          text-align: center;
          padding: 14px 16px;
          text-decoration: none;
          font-size: 17px;
      }
      
      /* Change the color of links on hover */
      .topnav a:hover {
          background-color: #ddd;
          color: black;
      }
      
      /* Add a color to the active/current link */
      .topnav a.active {
          background-color: #4CAF50;
          color: white;
      }
      
            
      body {
      }

      .sidenav a:hover {
          color: #f1f1f1;
      }
      
      .main {
          margin-top: 50px;
          margin-left: 300px; /* Same as the width of the sidenav */ 
          padding: 0px 10px;
      }      
      .main2 {
          margin-top: 50px;
          padding: 0px 10px;
      }

      /* On small screens, set height to 'auto' for sidenav and grid */
      @media screen and (max-height: 450px) {
        .sidenav {
            .sidenav {padding-top: 15px;}
            .sidenav a {font-size: 15px;}
        }
        .row.content {height: auto;} 
        
      }

      .btn {
          background-color: #f1f1f1;
          color: #111;
          font-size: 12px;
          text-transform:none;
      }
      table {
          border-collapse: collapse;
          width: 100%;
      }
      
      th, td {
          padding: 8px;
          text-align: center;
          border-bottom: 1px solid #ddd;
      }
      
      th {
          background-color: #e6f7ff;
      }
      
      tr:hover {background-color:#f5f5f5;}

    </style>
  </head>
  <body>

    <div class="topnav navbar-fixed-top">
      <a class="active" href="/">JJ_story</a>
      <a href="/posts/show">My Page</a>
      <a href="/users/edit">Edit Personal Info.</a>
   
      <ul class="topnav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: 'delete' %></li>
        <% else %>
          <li><a href="/users/sign_in">Sign in</a></li>
          <li><a href="/users/sign_up">Sign up</a></li>
        <% end %>
      </ul>

    </div>

    <div class="container-fluid">
      <div class="row content">
        <div class="col-sm-3 sidenav" style="margin-top:50px">
            <br>
 <% if user_signed_in? %>  
            <div class="w3-card w3-round w3-white">
        <div class="w3-container">
          
         <h3 class="w3-center" style="bold"><%= current_user.name %></h3>
         <hr>
         <p class="w3-center">
           
           <img src="<%= current_user.profile.url %>" class="img-circle" width="200px" height="auto">
          </p>
         <hr>
         <p><i class="fa fa-envelope fa-fw w3-margin-right w3-text-theme"></i> Email: <%= current_user.email %></p>
         <p><i class="fa fa-book fa-fw w3-margin-right w3-text-theme"></i> The number of posts: <%= @posts_count %></p>
         <p><i class="fa fa-sign-in fa-fw w3-margin-right w3-text-theme"></i> Follower: <%=current_user.followers.length %></p>
         <p><i class="fa fa-sign-out fa-fw w3-margin-right w3-text-theme"></i> Following: <%=current_user.followings.length %></p>
                     <div class="btn-group-vertical">

              <%= link_to new_post_path do %>
                <button class="btn btn-success navbar-btn">Write Post</button>
              <% end %> 
            </div>
        </div>
      </div>
      <br>
          <br>
          <% end %>
        </div>
        <%= yield %>
      </div>
    </div>


    
    
    
  </body>
</html>

app/views/posts/_post.html.erb
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<div>
    <br>
</div>
<div>
  <div style="padding-left:50px;padding-right:50px;padding-bottom:50px; border-left:1px solid #003300; border-right:1px solid #003300; border-top:1px solid #003300; border-bottom:10px solid; borderSpacing:15px">
    <hr><h2>
    <% if post.user.profile? %>
        <img class="img-circle" height="45px" width="45px"  src="<%= post.user.profile.url %>">
    <% end %>
    
    <%= post.user.name %>
    <% if user_signed_in? && current_user != post.user %>
        <% if current_user.followings.include?(post.user) %>
            <%= form_tag follow_path(post.user.id), method: :delete, class: "right" do %>
                <button class="btn btn-outline-success btn-sm">Unfollow</button>
            <% end %>
        <% else %>
            <%= form_tag follows_path, method: :post, class: "right" do %>
                <input type="hidden" name="followed_id" value="<%=post.user.id%>">
                    <button class="btn btn-outline-success btn-sm">Follow</button>
            <% end %>
        <% end %>
    <% end %>
    </h2>
    
    <h5><span><%= post.created_at %></span></h5>
    <hr>
    <% if post.image.url %>
        <img src="<%=post.image.url %>" class="img-size">
    <% end %>
    
    <p class="pre-line"><%= post.content %></p>      <hr>

    Like <%= post.likes.size %>s
    <% if current_user!=nil %>
        <% if current_user.is_like?(post) %>
            <button class="w3-button w3-green w3-round w3-tiny"><i class="fa fa-thumbs-up"></i><%= link_to "Unlike", post_like_path(post), method: "post" %></button>
        <% else %>
            <button class="w3-button w3-green w3-round w3-tiny"><i class="fa fa-thumbs-up"></i><%= link_to "Like", post_like_path(post), method: "post" %></button>
            
        <% end %>
        
        <% if current_user.id==post.user_id %>
            <%= link_to "Delete", post_path(post), method: "delete", class: "right" %>
            <br/>
            <%= link_to "Edit", edit_post_path(post),class: "right" %>
        <% end %>
    <% else %>
        <%= link_to "Like", post_like_path(post), method: "post" %>
    <% end %>
    

    <h4>Leave a Comment:</h4>
    
        <%= form_tag post_comments_path(post) do %> 
        <div class="input-filed">
            <%= text_area_tag :content, nil, required: true %> 
        </div>
        <div class="input-field"> 
            <%= button_tag "Comment", class: "btn" %> 
        </div>
        <% end %>
    
    <br><br>

      
    <p>Comments:(<%=post.comments.count%>)</p><br>
      
    <% if post.comments.present? %> 
        <div class="row">
	    <% post.comments.each do |comment| %> 
            <div class="col-sm-1 text-center">
              <img src="<%= comment.user.profile.url %>" class="img-circle" height="45px" width="45px" alt="Profile">
            </div>
            <div class="col-sm-11">
                <h4><%= comment.user.name %> <small><%= comment.created_at %></small></h4>
                <p class="pre-line"><%= comment.content %></p> 
                <% if current_user!=nil %>
                    <% if comment.user.id == current_user.id %> 
                        <div><%= link_to "delete", post_comment_path(post, comment), method: "delete" %></div> 
                    <% end %> 
                <% end %>
            </div>
            <br>
        <% end %>
        </div>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="main">
    <div class="container" style="margin-top: 50px; width:80%">
    <h2>Edit Post</h2>
    <br>
    <%= form_tag post_path(@post), method: "patch", multipart: true do %> 
        <input type="hidden" name="id" value="<%=@post.content%>"> 
        <div class="input-field"> <%= file_field_tag :image %> </div> 
        <br>
        <h4>Description</h4>
        <div class="input-field"><%= text_area_tag :content, @post.content, rows: 100, placeholder: "Description" %></div>
        <br>
        <div class="input-field"><%= button_tag "Edit", class: "btn" %></div>
    <% end %>
    </div>
</div>

app/views/posts/index.html.erb
<div class="main">
        <div class="container">
            <% @posts.each do |post| %>
                <%= render partial: "post", object: post %>
            <% end %>
        </div>
</div>

app/views/posts/new.html.erb
<div class="main">
    <div class="container" style="margin-top: 50px; width:80%">
    <h2>New Post</h2>
    <br>
    <%= form_tag posts_path, multipart: true do %>
        <div class="input-field">
            <%= file_field_tag :image %>
        </div>
        <br>
        <h4>Description</h4>
        <div class="input-field">
            <%= text_area_tag :content, nil, rows: 100, placeholder: "Description" %>
        </div>
                        
        <div class="input-field">
            <%= button_tag "Create", class: "btn" %>
        </div>
    <% end %>
    </div>
</div>

app/views/posts/show.html.erb
    
    
    <div class="row">
        <div class="main">
        <ul class="nav nav-pills nav-justified">
            <li class="active"><a data-toggle="pill" href="#my_posts">My Posts</a></li>
            <li><a data-toggle="pill" href="#following_posts">Following's Posts</a></li>
            <li><a data-toggle="pill" href="#follower_list">Follower (<%=current_user.followers.length %>)</a></li>
            <li><a data-toggle="pill" href="#following_list">Following (<%=current_user.followings.length %>)</a></li>
        </ul>
        </div>

        <div class="tab-content">
            <div id="my_posts" class="tab-pane fade in active">
                <div class="container">
                    <div class="row">
                        <div class="col s12 m2">
                        </div>    
                <div class="col s12 m10">        
                    <% @posts.each do |post| %>
                        <% if post.user.id==current_user.id %>
                            <%= render partial: "post", object: post %>
                        <% end %>
                    <% end %>
                </div>
                </div>
                </div>
            </div>
            <div id="following_posts" class="tab-pane fade">
                <div class="container">
                          <div class="row">
                        <div class="col s12 m2">
                        </div>    
                <div class="col s12 m10">   
                    <% @posts.each do |post| %>
                        <% if current_user.followings.include?(post.user) %>
                            <%= render partial: "post", object: post %>
                        <% end %>
                    <% end %>
                </div>
                </div>
                </div>
            </div>
    
            <div id="follower_list" class="tab-pane fade">
                <div class="container" style="margin-top:50px; margin-left:350px">
                    <table>
                        <thead>
                          <tr>
                              <th>Name</th>
                              <th>Email</th>
                              <th>Relationship</th>
                          </tr>
                        </thead>
                
                        <tbody>
                        <% current_user.follower_relations.each do |follower| %>
                          <tr>
                            <td><%= follower.follower.name %></td>
                            <td><%= follower.follower.email %></td>
                            <td>
                                <% if current_user.followings.include?(follower.follower) %>
                                    <%= form_tag follow_path(follower.follower.id), method: :delete, class: "right" do %>
                                        <button class="btn">Unfollow</button>
                                    <% end %>
                                <% else %>
                                    <%= form_tag follows_path, method: :post, class: "right" do %>
                                        <input type="hidden" name="followed_id" value="<%=follower.follower.id%>">
                                        <button class="btn">follow</button>
                                    <% end %>
                                <% end %>
                            </td>
                          </tr>
                         
                        <% end %>
                        </tbody>
                    </table>
                </div>
                
            </div>
        
            <div id="following_list" class="tab-pane fade">
                <div class="container" style="margin-top:50px; margin-left:350px">
                    <table>
                        <thead>
                          <tr>
                              <th>Name</th>
                              <th>Email</th>
                              <th>Relationship</th>
                          </tr>
                        </thead>
                
                        <tbody>
                        <% current_user.following_relations.each do |following| %>
                          <tr>
                            <td><%= following.followed.name %></td>
                            <td><%= following.followed.email %></td>
                            <td>
                                <%= form_tag follow_path(following.id), method: :delete, class: "right" do %>
                                        <button class="btn">unfollow</button>
                                <% end %>
                            </td>
                          </tr>
                         
                        <% end %>
                        </tbody>
                  </table>
                </div>
            </div>
        </div>
    </div>